### ISSUE TITLE
Establish academic integrity guidelines

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#101]
**Description of Issue:**

As RCOS is a course that will be taken for credit and will have a syllabus, we should have some academic integrity guidelines.

**Proposed Solution:**

Some ideas:
- Attendance codes must be logged honestly (attendance policy in bylaws)
   - First offense - unexcused absence for the day without ability to make up
   - Repeatedly logging false attendance or repeatedly distributing codes results in unexcused absence for all false attendance and referral to Dean of Students
- Pair programming is allowed as long as you give the other person credit.
- Asking for help from external sources is allowed and encouraged. 
  - However, please document this in your status updates so mentors & coordinators have a better understanding of your project status.
- Using source code, documentation, or graphics from other sources is allowed as long as you give proper attribution and it is permitted in the work's license. 
  - In fact, properly incorporating external open-source libraries and APIs is encouraged.
- Discussing your week-to-week status is encouraged, but all written status updates must be your own work. 
  - You may not write a status update for someone else or use someone else's status update as your own.
     - Duplicated status updates:
       - First offense:
         - If only one duplicated status update is found: both parties must rewrite their status update within a week or get a 0 and possible referral to Dean of Students.
         - Multiple weeks of duplicated status updates found: 0 on all duplicated status updates and referral to Dean of Students.
       - Second offense:
         - Single status update duplicated: both parties get a 0 on the status update for the week and  referred to Dean of Students.
         - Multiple weeks of status updates duplicated: treated as third offense.
       - Third or greater offense:
          - F in the course and referral to Dean of Students.
          - Ineligibility to become RCOS mentor.
    - Note that "duplicated status updates" refers to "blatantly copied" rather than "two students working together and doing separate but similar writeups".
  - If you are incorporating someone else's work (e.g. a tutorial on how to resolve an issue you have been having) into your status update, you must give proper attribution.

**Comment by aeksco** [comment]
Resolved by #111 - closing.
