### ISSUE TITLE
Create policy regarding extensions on status updates

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#102]
**Description of Issue:**
Extenuating circumstances may prevent students from submitting status updates on time.

**Proposed Solution:**
Possible options:
- Drop the lowest status update grade, 0 or otherwise (not including any status updates that received a 0 for academic dishonesty)
  - Potential problem: this may lead to a large number of students not submitting status updates on the last week
- Coordinators or faculty advisors may grant an extension until Tuesday for extenuating circumstances:
  - Student has an excused absence on that Friday
  - Fire alarm goes off in the building where Friday smallgroup occurs
  - Building where Friday smallgroup occurs is evacuated for another reason
  - Student is having problems logging into Observatory
  - Observatory is down
     - In the event of Observatory being down, status update deadline will be pushed to Tuesday

**Comment by Apexal** [comment]
This will be handled by #150
