### ISSUE TITLE
Attendance policy when Observatory is down

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#103]
**Description of Issue:**
We have had at least one incident this semester where Observatory was down.

**Proposed Solution:**
- Large group (and potentially small group): mark everyone as excused or do not count that day when grading attendance
- Small group or bonus session: mentor passes around an attendance sheet and at the end of the session submits to coordinator. Everyone who signed that sheet gets manually marked present. Signing in anyone but yourself counts as dishonestly logging attendance.

**Comment by Apexal** [comment]
As we now use Venue, this can be closed.
