### ISSUE TITLE
Inclement weather policy

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#105]
**Description of Issue:**
Currently, there is no documented policy on cancellations due to inclement weather.

**Proposed Solution:**
- Required sessions and weekday bonus sessions: if classes are not in session due to inclement weather, RCOS and any bonus sessions scheduled for that day will not meet. This is already implied, but this creates an issue for weekend sessions where classes are already not in session.
- Weekend casual coding sessions: cancel if shuttle service, CDTA, or Safe Ride is not running due to inclement weather
- Weekend code jams, hackathons, one-time-only weekend bonus sessions: see above, possibly reserve a snow date as well during the last month of the fall semester or first half of the spring semester

**Comment by aeksco** [comment]
Adding the backlog tag here as dealing with inclement weather will be less of a priority for the next semester :+1:

**Comment by aeksco** [comment]
Resolved by #111 - closing.
