### ISSUE TITLE
Add speed dating documentation

### ISSUE THREAD

**Issue by Bad-Science** [rcos/rcos-handbook#11]
**Description of Issue:**

Documentation of speed dating is incomplete

**Proposed Solution:**

Old speed dating document from rcos/intro should be added. The document should be updated with new organization details, and history of why speed dating was created.

**Comment by aeksco** [comment]
Partially resolved by PR #48 - copied old speed dating documentation from `rcos/intro`

We still need to update the document to detail:
- Why speed dating was created
- How speed dating is organized 

We should re-think how speed dating is handled - the spring 2018 semester was a bit chaotic

**Comment by kburk1997** [comment]
Absolutely --- perhaps use a different room than DCC 318 for all the projects? We could use multiple rooms downstairs and put a few projects in each room, but we should definitely have at least one or two rooms for proposal review.

**Comment by aeksco** [comment]
Definitely - we need to have some stronger organization for Proposals & Speed Dating - separate rooms would be good start for sure. I think projects presenting at speed dating should be in one room, and proposal review should be in another. DCC 318 really isn't suitable for anything that isn't a lecture / presentation.

I think we should also outline some requirements for projects that are presenting at speed dating. We also need some better way to know wether or not a project is presenting at speed dating - in the past I think we've used a Google Form, but those haven't really been serving us well as RCOS has grown.

**Comment by aeksco** [comment]
Assigned to Varun Rao

**Comment by vkr96** [comment]
[speedating_handbook.txt](https://github.com/rcos/rcos-handbook/files/2334423/speedating_handbook.txt)

**Comment by aeksco** [comment]
Attached to #74
