### ISSUE TITLE
Bonus session requirement

### ISSUE THREAD

**Issue by vakrao** [rcos/rcos-handbook#115]
**Description of Issue:**

Workshop Requirement 

**Proposed Solution:**

Add details on bonus sessions. Specifically, that all students must attend at least one workshop bonus session OR volunteer for a CS event a semester. Casual coding sessions or other bonus sessions do not count towards this requirement. Casual coding sessions, other bonus sessions, or extra workshops that go beyond the required one workshop can count towards unexcused absences. 

Also, add section in handbook about mentors being required to hold at least one workshop a semester.

**Comment by Apexal** [comment]
Current coordinators and faculty advisors need to discuss what the requirements going forward are. The Handbook had conflicting information about 50% attendance while we were going with at least 1. Personally I think somewhere in between is best as I've only heard of and personally experienced useful and engaging workshops at RCOS.

**Comment by wdturner** [comment]
We should set up a meeting early in the week of 1/11/2021 to discuss this and the Spring 2021 semester.

**Comment by Apexal** [comment]
> We should set up a meeting early in the week of 1/11/2021 to discuss this and the Spring 2021 semester.

Agreed. I created a column on the Spring 2021 project board for an agenda: https://github.com/orgs/rcos/projects/4#column-12320706

**Comment by Apexal** [comment]
Taking this on now as the Handbook currently has conflicting information.
