### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by Apexal** [rcos/rcos-handbook#120]
**Description of Issue:**
While there are detailed descriptions of how RCOS works and the mission statement is clearly stated, it is not clear for absolute newcomers. I just had a incoming freshman message me about what RCOS actually did after reading rcos.io and not really understanding how it worked!

**Proposed Solution:**
A Frequently Asked Questions page could answer the following questions all in one place:
- What do you do in RCOS?
- What kind of course credit can you receive?
- How often does RCOS meet?
- How much time is expected per week?
- What kind of projects can I work on?
- Why is RCOS a unique RPI organization?

While some of these answers are addressed across the handbook, website, or Mattermost, it would be useful to have a page we can direct students to.

**Comment by aeksco** [comment]
I think we should consolidate that into the handbook for now and post links in the #welcome channel on Discord 👍

**Comment by Apexal** [comment]
We were asked to prepare two short intro slides to present at the Freshman CS Club Fair. I will throw in some of these practical FAQ questions there!
