### ISSUE TITLE
Update to use Vuepress

### ISSUE THREAD

**Issue by aeksco** [rcos/rcos-handbook#127]
**Description of Issue:**

Docsify was a decent solution to get this project off the ground, but we would be better served if we built a static site using [VuePress](https://vuepress.vuejs.org/). It would be great to support improved search by having a statically-generated site (Docsify is built entirely at runtime).

**Why [VuePress](https://vuepress.vuejs.org/)?** I've done a survey of the available documentation site generators and VuePress is _by far_ the simplest option in terms of deployment and local development.

I surveyed the following:
- Docsify (currently used for `handbook.rcos.io`)
- VuePress
- Docasaurus 
- Gatsby
- GitBook
- Jekyll

**Proposed Solution:**

We migrate the site to use Vuepress and deploy it through Netlify.

**Comment by rushsteve1** [comment]
Superseded by #140
