### ISSUE TITLE
Presentation Guidelines

### ISSUE THREAD

**Issue by Apexal** [rcos/rcos-handbook#142]
**Is your feature request related to a problem? Please describe.**
The Final Presentation page is lacking in some details.

**Describe the solution you'd like**
Add a couple example presentations from previous semesters.

**Comment by rushsteve1** [comment]
A looong while ago @OliviaLundelius and @AdrianCollado gave a tall on how to give a good presentation.

**Comment by hbh7** [comment]
Feel free to add Poll Buddy's Fall 2020 presentation if that helps :) 
https://docs.google.com/presentation/d/1kso5zVST9BMJ47kN0e3hdFemxm11NBhn8GuBnMhyT8U/edit
