### ISSUE TITLE
Describe note-taking rules

### ISSUE THREAD

**Issue by Apexal** [rcos/rcos-handbook#148]
We've decided to use the https://github.com/rcos/rcos-notes repository to keep meeting notes. There should be one Coordinator assigned to take notes at Coordinator meetings for the semester, and there should be a backup in case they miss meetings. The Handbook should detail this process.

**Comment by bnidevs** [comment]
would you like me to perform the duty of scribe

**Comment by Apexal** [comment]
@bnidevs Could you add a Handbook page under Coordinators detailing the process of taking meeting notes in `rcos/rcos-notes`? And then if you'd like to fulfill that role for the rest of semester, that'd be great 😎
