### ISSUE TITLE
Number of Status Updates Required 

### ISSUE THREAD

**Issue by Apexal** [rcos/rcos-handbook#150]
**Is your feature request related to a problem? Please describe.**
Currently we allow students to miss 2 Status Updates without penalty. This is not documented explicitly in the Handbook, which just states that you must submit the "required amount" of Status Updates.

**Describe the solution you'd like**
Explicitly state the number of Status Updates required to submit.

**Comment by Apexal** [comment]
How do we feel about allowing only 2 missed Status Updates without penalty? 4 actually seems extremely high, considering how few there are in total. Especially if the semester's going to be partially or totally online, Status Updates are very important for Mentors to understand where their mentees are. @rcos/current-leadership

**Comment by hbh7** [comment]
Makes sense to me

**Comment by wdturner** [comment]
We’ll need to get together before the semester starts. Let’s add this to the agenda as something to discuss.

Prof. Turner

**Comment by bnidevs** [comment]
see #159 159
