### ISSUE TITLE
Appealing Grades

### ISSUE THREAD

**Issue by aeksco** [rcos/rcos-handbook#19]
**Description of Issue:**

We don't have any documentation about appealing grades

**Proposed Solution:**

We discuss potential solutions here @AdrianCollado @kburk1997 @Bad-Science 

I personally feel one of the following options should be in place:

**Option A**: An appeal process that takes place _after_ the grade is entered in SIS with a period of X days (i.e. Mon-Fri of the week AFTER grading) to request a grade appeal. We would provide a template for the request to simplify the process.

**Option B**: We produce an algorithm to calculate a student's grade on-the-fly for an always-up-to-date calculated grade for the class. 

**Options C**: ???

**Comment by kburk1997** [comment]
Option B seems very complicated as a lot of grading criteria in RCOS can be very subjective. I also don't know how Option A would work if we can't schedule a "final exam" for RCOS as final grades are due within 48-72 hours of the final exam.

**Comment by aeksco** [comment]
@kburk1997 I agree `Option B` is going to be too much work and it doesn't mesh with the flexibility of our grading rubric. 

I think after seeing how things went over the past week we can go with `Option A` - essentially provide a grace period of X days (I think 7 is reasonable) to appeal a grade. After revisiting this after a week I think providing a Markdown or PDF template for a Grade Appeal will streamline the process nicely. I've outlined a list of basic requirements for that below:

**Grade Appeal Template**
- Student Name / GitHub / RCS
- GitHub Issues / Milestones
- Blog Posts
- Attendance History - Large Group, Small Group, Bonus Sessions
- Comments / Additional Information
