### ISSUE TITLE
Add documentation for hosting an event

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#30]
**Description of Issue:**

Hosting an event documentation is incomplete.
**Proposed Solution:**

Outline criteria/requirements

**Comment by aeksco** [comment]
Docs should include:
- Who to contact (talk to coordinators and faculty advisors)
- How to reserve a room (talk to coordinators and faculty advisors)
- Requirements for event - must be one of the following:
  - Tech talk
  - Info session
  - Code jam
  - External volunteering

**Note on events**:
- all RCOS events are _dry_ - no alcohol may be consumed during a sanctioned event. 
- All events must end before 12 midnight (Hackathons notwithstanding)
- All events must begin at 9am or later
