### ISSUE TITLE
Flesh out RCOS teams

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#33]
**Description of Issue:**

There are still some TODO items on RCOS teams:
- describe purpose of RCOS teams
- document process of joining teams
**Proposed Solution:**

Complete the above TODO items as well as any additional documentation.

**Comment by aeksco** [comment]
Notes from 8/20/18 Coordinator Meeting:


## RCOS Teams
- If you work on a team you are essentially working on things that are important to running RCOS
- Each team should have one mentor to 
- Document how to go into a team
- Sponsorship, outreach, managing funds would be some of the responsibilities of a RCOS team
- For fungible assets there needs to be faculty - for first semester this would not be needed 

#### Outreach
- Management of tech speakers making sure we have a wide range of guest speakers 
- Outreach -> find interesting speakers 
- Maintain a list of past speakers
- Need to have more diverse speakers!
- students interface with interesting companies to explore more sponsorship opportunities with RCOS 
- leverage the fact that we have a massive open source community to lure interesting sponsors

#### Volunteering  (from RCOS to outside of RPI)
- Milena, Grace did a lot of volunteering events 
- More opportunities for this type of outreach
- Doing this in a more official capacity would be superb

**Comment by wdturner** [comment]
Excellent comments

**Comment by aeksco** [comment]
Resolved by PR #74

**Comment by aeksco** [comment]
b
