### ISSUE TITLE
Establish threshold percentage that must be fulfilled by regular attendance

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#34]
**Description of Issue:**

This is a TODO item in "attendance"
**Proposed Solution:**

Establish this threshold. Also, figure out how excused absences factor in to this. Do we throw away excused absences and only count % of regular sessions vs % bonus sessions or will excused absences count towards the percentage of regular sessions?

**Comment by kburk1997** [comment]
Would anywhere between 50-70% be reasonable? 50 is probably lowballing but we only have so many sessions in the semester. Also, how would small group vs large group work? I feel like the threshold for small group should ideally be higher than large group because that's where a lot of project work is done

**Comment by kburk1997** [comment]
@aeksco @AdrianCollado @Bad-Science @wdturner we should have this fleshed out before the semester begins

**Comment by wdturner** [comment]
I would keep this high. Maybe as much as no more than 2 unexcused absences
may be made up. If there is an excused reason to miss more than that, fine.
I do like the wording on the exception process.

**Comment by Apexal** [comment]
We have been working with 2 excused missed attendances, with the ability to make them up with workshop attendance. Closing this as that rule is listed in the Handbook rubric.
