### ISSUE TITLE
Finish information regarding sponsors

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#45]
**Description of Issue:**

In Sponsors, we still have "TODO: information regarding sponsors goes here".

**Comment by kburk1997** [comment]
Partially resolved by #52.

TODO: address the following:
- How to become a sponsor
- How to donate to RCOS
- Link to contact information

Perhaps we should split the above into separate issues. @aeksco thoughts on splitting this into three issues vs. the current issue?

**Comment by wdturner** [comment]
I just sent a note to coordinators on donating to RCOS. We need this front
and center on our site and handbook ... At least until we hear we are not
allowed to publicize ... :-)

- Wes

**Comment by Apexal** [comment]
I'll pick this up and determine its current status with Prof. Turner.

**Comment by Apexal** [comment]
We've moved sponsor info to https://rcos.io/sponsors
