### ISSUE TITLE
Establish protocol for creating, storing, regenerating passwords

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#47]
**Description of Issue:**

TODO in coordinating/passwords

**Comment by aeksco** [comment]
Removing this from backlog - going to be outlining some procedures here with @Apexal so we have a centralized + secure location for passwords going forward :+1:

**Comment by Apexal** [comment]
I created a hosted BitWarden account under the new rcos.management@gmail.com email address and sent the password to all current coordinators and faculty advisors. I'm consolidating all of our infrastructure and social media passwords there, and we will look to moving it to our own servers once we get a hold of them!
