### ISSUE TITLE
Update agenda

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#61]
**Description of Issue:**

In the coordinator meetings on August 13 and 20, we discussed a few changes to the agenda so we can have small group meetings start earlier on in the semester.

**Proposed Solution:**

Keeping this information available only to coordinators and to mentors during the mentor training is against our open-source ethos. We should update the "First Two Weeks" document ASAP.

**Comment by aeksco** [comment]
Update [First Week Agenda](https://handbook.rcos.io/#/coordinating/agenda) in handbook

**Comment by aeksco** [comment]
@AdrianCollado You've got notes about how we're restructuring the first few weeks?

**Comment by kburk1997** [comment]
Those changes were placed in our mentor training documentation

**Comment by wdturner** [comment]
Third meeting refers to the fourth meeting instead.

**Comment by aeksco** [comment]
Looks like this was resolved in #107 - closing.
