### ISSUE TITLE
Provide information on how to request an excused absence pre-Observatory

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#63]
**Description of Issue:**

Observatory still does not have functionality to request an excused absence. Currently, there is no documentation on how to request an excused absence without Observatory.

**Proposed Solution:**

Add documentation detailing our current method of resolving excused absences.

**Comment by aeksco** [comment]
This is detailed in issue #68 - I'll mark this as closed and move the discussion there
