### ISSUE TITLE
Document process for resolving administrative errors in attendance data

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#66]
**Description of Issue:**

Currently, there is documentation for requesting excused absences, but no documentation for correcting any errors in attendance data (e.g. a student was present but a glitch in Observatory marked it as an unexcused absence).

**Proposed Solution:**

Add process for resolving attendance issues under `grading/attendance.md`. 

Draft process: 

To be marked as PRESENT: Contact one of your small group mentors or, if you attended a bonus session, the mentor(s) who hosted the bonus session. If they verify that you were present, they will then contact a coordinator, who will manually mark you as present.

To be marked as EXCUSED: If you have requested an excused absence, but it shows up as unexcused after [insert time period], contact a coordinator or faculty advisor. They will then review your request, and may then mark you as excused.

Also, we need to determine a reasonable time period to resolve excused absences.

**Comment by Apexal** [comment]
Addressed.
