### ISSUE TITLE
Establish deadline for requesting an excused absence

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#68]
**Description of Issue:**

Right now, we have no documented deadline for requesting an excused absence. This means that theoretically, people can send out excused absence requests en masse at the end of the semester.

**Proposed Solution:**

Establish a deadline for requesting an excused absence. This may require a distinction between foreseen and unforeseen absences. If this already exists somewhere, document it.

Draft policy:

>For foreseen absences (e.g. religious holidays, job/grad school interviews, weddings, hackathons), you must request an excused absence no later than [x] day(s) in advance.

x days can be anywhere from as little as 1 day to 7 days.

> For unforeseen absences (e.g. illness, family emergency), you must request an excused absence no later than [y] days/week(s) after you return to RCOS.

y can range from 3 days to 2 weeks.

Of course, we can make exceptions on a case by case basis:

> Exceptions may be made on a case-by-case basis, but proper documentation is required.

**Comment by aeksco** [comment]
Related to issue #63

**Comment by aeksco** [comment]
For foreseen absences: a student must provide at least 48 hours notice

For unforeseen absences: a student must report the absence within 1 week of the return date

Make a note - for extenuating circumstance please speak to a coordinator or adviser directly.
