### ISSUE TITLE
Sensitive topics in project talks

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#8]
**Description of Issue:**

As our organization grows, we are starting to get more "off-topic" talks. This increases the potential for an inevitable talk on sensitive material, which could ultimately contribute to a hostile environment since students at large group are mandated to attend and thus cannot leave if they feel uncomfortable.

**Proposed Solution:**

Outline a policy in Bylaws on sensitive topics.

**Comment by aeksco** [comment]
Presentations should not include any content that is:
- Sexually charged
- Discriminatory
- Incites violence or hate
- Contains excessive profanity

If you're unsure about whether or not your talk conforms to the above guidelines, please reach out to a mentor or coordinator to discuss.
