### ISSUE TITLE
Add Links to meeting times + locations, presentation schedule

### ISSUE THREAD

**Issue by aeksco** [rcos/rcos-handbook#82]
**Description of Issue:**

Observatory will no longer be responsible or showing RCOS meeting times and presentation schedule - the handbook is a much easier solution for maintaining this data.

**Proposed Solution:**

We add some links to the home page that directs interested parties towards our calendar of events and our presentation schedule.

**Comment by Apexal** [comment]
I am exploring ways to automatically generate a calendar from our central database being developed. I will be sure to link it from the handbook along with the Webex link for online meetings.
