### ISSUE TITLE
Students pursuing RCOS for experience don't need to produce Status Updates

### ISSUE THREAD

**Issue by aeksco** [rcos/rcos-handbook#85]
**Description of Issue:**

Students pursuing RCOS for experience are not required to produce Status Updates - this isn't documented anywhere.

**Proposed Solution:**

This should be documented on the [Status Updates](https://handbook.rcos.io/#/grading/status_updates) page of the Handbook.

**Comment by Apexal** [comment]
We should determine if this is still the case for this semester onwards

**Comment by Apexal** [comment]
This was discussed with Prof Turner. I am adding a general note on the grading overview page explaining that students not enrolled for credit are under no obligation to submit anything and attendance is not required.
