### ISSUE TITLE
Add "referral to Dean of Students" as a potential consequence for CoC violations in Bylaws

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#87]
**Description of Issue:**

Currently, we have no protocol to handle incidents that violate both the RCOS Code of Conduct and/or Bylaws and the RPI Student Handbook.

**Proposed Solution:**

Add "Referral to Dean of Students for infractions of the RPI Student Handbook" as one of the consequences under Bylaws

**Comment by vakrao** [comment]
I think we should also add a link to the RPI Student Handbook, and state that all members must follow all the policies outlined in it.
